/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: imperishability (https://sketchfab.com/imperishability)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gate-ef97e30879194b7ab1901110c9756b87
title: Gate
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    zabor_Cube000_0: THREE.Mesh
    kolonny_Cube000_0: THREE.Mesh
  }
  materials: {
    ['metall.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/gate.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.zabor_Cube000_0.geometry} material={materials['metall.001']} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.kolonny_Cube000_0.geometry} material={materials['Material.005']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gate.gltf')
