/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DJMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tree-1d26dcc1af0c4a06a95c459b7ca4cf6f
title: Tree
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    leaves_branches_0: THREE.Mesh
    tree2_tree2_0: THREE.Mesh
  }
  materials: {
    branches: THREE.MeshStandardMaterial
    tree2: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/tree.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 5.82, 0]}>
            <group position={[2.24, 326.77, 19.79]}>
              <mesh geometry={nodes.leaves_branches_0.geometry} material={materials.branches} />
            </group>
            <mesh geometry={nodes.tree2_tree2_0.geometry} material={materials.tree2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree.gltf')
