/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DJMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/trees-dbd3f20966de4cae9170413b9c6f891d
title: Trees
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    branches_branches_0: THREE.Mesh
    tree1_tree1_0: THREE.Mesh
    branches_2_branches_0: THREE.Mesh
    tree2_tree2_0: THREE.Mesh
    branches_3_branches_0: THREE.Mesh
    tree3_tree3_0: THREE.Mesh
  }
  materials: {
    branches: THREE.MeshStandardMaterial
    tree1: THREE.MeshStandardMaterial
    tree2: THREE.MeshStandardMaterial
    tree3: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/trees.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-5.6, 5.1, -8.66]}>
            <group position={[-147.78, 6.72, 81.25]}>
              <group position={[-0.28, 150.18, 16.95]}>
                <mesh geometry={nodes.branches_branches_0.geometry} material={materials.branches} />
              </group>
              <mesh geometry={nodes.tree1_tree1_0.geometry} material={materials.tree1} />
            </group>
            <group position={[271.33, -3.72, -16.63]} rotation={[Math.PI, 1.53, -Math.PI]}>
              <group position={[-201.75, 359.98, 124.92]} rotation={[Math.PI, -1.53, -Math.PI]}>
                <mesh geometry={nodes.branches_2_branches_0.geometry} material={materials.branches} />
              </group>
              <mesh geometry={nodes.tree2_tree2_0.geometry} material={materials.tree2} />
            </group>
            <group position={[-446.34, -3, -73.89]} rotation={[0, -1.03, 0]}>
              <group position={[-108.07, 409.93, 86.31]} rotation={[0, 1.03, 0]}>
                <mesh geometry={nodes.branches_3_branches_0.geometry} material={materials.branches} />
              </group>
              <mesh geometry={nodes.tree3_tree3_0.geometry} material={materials.tree3} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/trees.gltf')
